### ISSUE TITLE
Hotkeys enabled in OTClient

### ISSUE THREAD

**Issue by peonso** [Ezzz-dev/OTHire#58]
Players can use item Hotkeys and attack players through Battle Window with OTClient

https://otland.net/threads/7-72-othire-0-0-1b-based-in-otserv-trunk-latest.212153/page-18#post-2082195

**Comment by diegorodriguesvieira** [comment]
I have a server 7.6, and I blocked these options in OTClient, if you can show you how I did ...

**Comment by diegorodriguesvieira** [comment]
#72

**Comment by peonso** [comment]
That shit can't be solved, don't think we do any good pointing out it even exists.

@diegorodriguesvieira

**Comment by peonso** [comment]
> That shit can't be solved, there is nothing to be done server side, don't think we do any good pointing out it even exists. Better that can be done is to edit your own client.
> 
> @diegorodriguesvieira

This actually should be solveable server side. TFS has a solution.

https://github.com/otland/forgottenserver/blob/6143815cb9230cce94de47313595567f9f51ea70/src/game.cpp#L2089-L2092
https://github.com/otland/forgottenserver/blob/6143815cb9230cce94de47313595567f9f51ea70/src/game.cpp#L2177-L2180
https://github.com/otland/forgottenserver/blob/6143815cb9230cce94de47313595567f9f51ea70/src/game.cpp#L2247-L2253

**Comment by peonso** [comment]
> > That shit can't be solved, there is nothing to be done server side, don't think we do any good pointing out it even exists. Better that can be done is to edit your own client.
> > @diegorodriguesvieira
> 
> This actually should be solveable server side. TFS has a solution.
> 
> https://github.com/otland/forgottenserver/blob/6143815cb9230cce94de47313595567f9f51ea70/src/game.cpp#L2089-L2092 https://github.com/otland/forgottenserver/blob/6143815cb9230cce94de47313595567f9f51ea70/src/game.cpp#L2177-L2180 https://github.com/otland/forgottenserver/blob/6143815cb9230cce94de47313595567f9f51ea70/src/game.cpp#L2247-L2253

After studying otclient a bit I think it's actually easy to make a module that bypass forgottenserver block.
